#!/usr/bin/env python2
#
# Copyright 2015 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from tuscan.tuscan_build import do_build
from tuscan.tuscan_postprocess import do_postprocess
from tuscan.tuscan_html import do_html
from tuscan.tuscan_figures import do_figures

from argparse import ArgumentParser
from multiprocessing import cpu_count
from os import listdir


def main():
    parser = ArgumentParser(description=
               "Run corpus-based toolchain experiments.")

    subparsers = parser.add_subparsers(dest="command")

    # ./tuscan.py build
    build_parser = subparsers.add_parser("build",
            help="Build all packages with a particular toolchain.")
    build_parser.set_defaults(func=do_build)

    toolchains = listdir("toolchains/make_package")
    build_parser.add_argument("toolchain", choices=toolchains,
            help="a toolchain, configured in a subdirectory of"
                 " toolchains/.")

    build_parser.add_argument("-v", "--verbose", action="store_true",
            help="show Docker output")

    build_parser.add_argument("--top-level", dest="top_level",
            metavar="TARGET",
            help="override the top-level target to build.")

    build_parser.add_argument("--no-run", action="store_false",
            dest="run", help="Set up containers, but don't run ninja.")

    # ./tuscan.py postprocess
    postprocess_parser = subparsers.add_parser("post",
            help="Post-process results generated by tuscan build.")

    toolchains = listdir("output/post")
    postprocess_parser.add_argument("--toolchains", default=toolchains,
            nargs="*", choices=toolchains, help="which toolchains to"
            " post-process (default: '%s')" % " ".join(toolchains))

    postprocess_parser.add_argument("-j", "--jobs", type=int,
            metavar="N", default=cpu_count(), dest="pool_size",
            help=("Number of parallel subprocesses to launch"
                  " (default=%d)" % cpu_count()))

    postprocess_parser.add_argument("-t", "--timeout", type=int,
            metavar="N", default=1200,
            help=("Kill post-processing if it takes longer than"
                  " N seconds (default=%d)" % 1200))

    postprocess_parser.set_defaults(func=do_postprocess)

    # ./tuscan.py html
    html_parser = subparsers.add_parser("html",
            help="Generate HTML reports of post-processed data.")

    html_parser.add_argument("-j", "--jobs", type=int,
            metavar="N", default=cpu_count(), dest="pool_size",
            help=("Number of parallel subprocesses to launch"
                  " (default=%d)" % cpu_count()))

    html_parser.add_argument("-t", "--timeout", type=int,
            metavar="N", default=1200,
            help=("Kill HTML generation if it takes longer than"
                  " N seconds (default=%d)" % 1200))

    html_parser.set_defaults(func=do_html)

    # ./tuscan.py figures
    figures_parser = subparsers.add_parser("figures",
            help="Generate figures from post-processed data.")

    figures_parser.set_defaults(func=do_figures)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
