#!/usr/bin/env python2
#
# Copyright 2016 Kareem Khazem. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.


import datetime
import voluptuous
import yaml


# We can't merely specify that strings ought to be of type 'str' in the
# schemata, since Python 2.7 treats unicode strings specially.
_nonempty_string = voluptuous.All(voluptuous.Any(str, unicode), voluptuous.Length(min=1))
_string = voluptuous.All(voluptuous.Any(str, unicode))


"""voluptuous.Schema for the deps.yaml files located in each stage directory"""
stage_deps_schema = voluptuous.Schema({
    # The name of the stage (this does not exist in the deps.yaml file
    # itself, but is added to the data structure after the file is read)
    voluptuous.Required("name"): _nonempty_string,
    # Data needed to build the container
    voluptuous.Required("build"): voluptuous.Schema({
        # Stages that need to have run before we build this stage
        voluptuous.Optional("stages"): [_nonempty_string],
        # Files that we need to copy into the build context (i.e. files
        # that are mentioned in the Dockerfile, or are needed for some
        # other reason)
        voluptuous.Optional("copy_files"): [_nonempty_string],
        # Script that should be run just before the Docker build command
        voluptuous.Optional("script"): _nonempty_string,
    }),
    # Data needed to run the container
    voluptuous.Required("run"): voluptuous.Schema({
        voluptuous.Optional("dependencies"): voluptuous.Schema({
            #Stages that need to have run before we run this stage
            voluptuous.Optional("stages"): [_nonempty_string],
            # Data containers that are used during the run of this stage
            voluptuous.Optional("data_containers"): [_nonempty_string],
            # Directories that will be mounted in this stage's
            # container. This dictionary mounts the local directory to
            # the directory it will be mounted under in the container.
            voluptuous.Optional("local_mounts"): {
                _nonempty_string: _nonempty_string
            },
        }),
        # Instead of doing 'docker run', run a custom command
        voluptuous.Optional("command_override"): _nonempty_string,
        # Redirect the running container's output to a file
        voluptuous.Optional("stdout"): _nonempty_string,
        voluptuous.Optional("stderr"): _nonempty_string,
        # Do a shell command after this stage's container exits
        voluptuous.Optional("post_exit"): _nonempty_string,
        # Indicates that this stage is the root of the dependency tree
        # (the final stage to be run), and may take over the console
        voluptuous.Optional("top_level"): bool,
        # Whether to pass the --rm flag to docker run
        voluptuous.Optional("rm_container"): bool,
    })
})


"""voluptuous.Schema for data_containers.yaml file"""
data_containers_schema = voluptuous.Schema([
    voluptuous.Schema({
        # The Docker name of this data container
        voluptuous.Required("name"): _nonempty_string,
        # Where the data container will be mounted
        voluptuous.Required("mountpoint"): _nonempty_string,
        # We pass the location of data containers to stages using a
        # command line argument. We relate locations to the command line
        # switch using this key, such that if we have a data container
        # specified like this:
        # {"mountpoint": "/toolchain", "switch": "toolchain-dir"}
        # then any stage that uses this data container will get the
        # command-line argument
        # --toolchain-dir /toolchain
        voluptuous.Required("switch"): _nonempty_string
    })
])


# The kinds of errors that red might report
red_error_categories = [
    "hardcoded invocation",
    "empty path",
    "malformed path",
    "PATH not in env!",
]


"""voluptuous.Schema for JSON files that are generated by the make_package stage"""
make_package_schema = voluptuous.Schema({
    voluptuous.Required("build_name"): _nonempty_string,
    # This will be true for bootstrap packages, and false otherwise.
    # The results of boostrap packages will not fully conform to this
    # schema (see tuscan/empty.json for what fields bootstrap packages
    # have); clients should not attempt to validate results of bootstrap
    # packages.
    voluptuous.Required("bootstrap"): bool,
    voluptuous.Required("return_code"): voluptuous.All(int,
        voluptuous.Range(min=0)), voluptuous.Required("time"):
    voluptuous.All(int, voluptuous.Range(min=0)),
    voluptuous.Required("toolchain"): _nonempty_string,
    voluptuous.Required("errors"): list,
    # What packages are provided by this build? This will be a list of
    # package names, possibly including meta-packages (like 'sh') that
    # don't really exist but are provided by bash.
    voluptuous.Required("build_provides"): list,
    # What packages are depended on by this build? This will be a list of
    # package names, possibly including meta-packages (like 'sh') that
    # don't really exist but are provided by bash.
    voluptuous.Required("build_depends"): list,
    # Map from languages in this build, to how many LOC are written in
    # that language.
    voluptuous.Required("sloc_info"): voluptuous.Schema({
        _nonempty_string: int
    }),
    # Errors logged by the red tool.
    voluptuous.Required("red_errors"): [
        voluptuous.Schema({
            voluptuous.Required("category"):
                voluptuous.Any(*red_error_categories),
            voluptuous.Required("pid"): _nonempty_string,
            voluptuous.Required("info"): _string
        })
    ],
    # Output from the red tool wrapping the makepkg command.
    voluptuous.Required("red_output"): voluptuous.Schema([ voluptuous.Any(
        voluptuous.Schema({
            "kind": "exit",
            "pid": _nonempty_string,
            "ppid": _nonempty_string,
            "return_code": _nonempty_string
        }),
        voluptuous.Schema({
            "kind": "exec",
            "timestamp": _nonempty_string,
            "pid": _nonempty_string,
            "ppid": _nonempty_string,
            "directory": _nonempty_string,
            "function": _nonempty_string,
            "command": [ _string ]
        })
    )]),
    voluptuous.Required("log"): [
        # Logs have a head and body. Typically, for each command that
        # gets executed by the make_package stage, the head will be the
        # command and the body will be the output of that command.
        # Some log structures might have an empty body, though.
        voluptuous.Schema({
            voluptuous.Required("head"): _nonempty_string,
            voluptuous.Required("kind"): voluptuous.Any("command", "info", "die"),
            voluptuous.Required("time"): (lambda s:
                datetime.datetime.strptime(s, "%Y-%m-%dT%H:%M:%S")),
            voluptuous.Required("body"): [
                voluptuous.Schema(_string)
            ]
        })
    ]
})


with open("tuscan/classification_patterns.yaml") as f:
    _patterns = yaml.load(f)
_categories = [p["category"] for p in _patterns]


# Voluptuous doesn't support recursive schemata, so we need to use this
# trick. After post-processing, the process tree shall be a recursive
# data structure.

def _red_record_1(v):
    return _red_record(v)

_red_record = voluptuous.Schema({
    "children": voluptuous.Any([_red_record_1], []),
    "timestamp": int,
    "return_code": voluptuous.Any(int, None),
    "command": voluptuous.Any(_nonempty_string, None),
    "pid": int,
    "ppid": voluptuous.Any(int, None),
    # How the command was spawned: execve, posix_spawn etc.
    "function": voluptuous.Any(_nonempty_string, None),
    # Errors in the way that this command was spawned, detected by red.
    "errors": [
        voluptuous.Schema({
            "category": voluptuous.Any(*red_error_categories),
            "info": _string,
        })
    ],
})


"""voluptuous.Schema for JSON files dumped out of the post-processing stage"""
post_processed_schema = voluptuous.Schema({
    voluptuous.Required("build_name"): _nonempty_string,
    voluptuous.Required("bootstrap"): bool,
    voluptuous.Required("return_code"): voluptuous.All(int,
        voluptuous.Range(min=0)),
    voluptuous.Required("time"): voluptuous.All(int, voluptuous.Range(min=0)),
    voluptuous.Required("toolchain"): _nonempty_string,
    voluptuous.Required("build_provides"): list,
    voluptuous.Required("build_depends"): list,
    # Was there no source available for this build?
    voluptuous.Required("no_source"): bool,
    # Which packages is this build blocking? If this package failed to
    # build but all its dependencies built successfully, then this
    # package is said to be a "blocker" and this list will contain all
    # packages that transitively depend on it.
    voluptuous.Required("blocks"): [_nonempty_string],
    # Which builds are blocking this build? If a build of this package
    # was not attempted because some of its dependencies failed to
    # build, then this list will contain those dependencies. Note that
    # if A blocks B from building and C depends on B, then A (but not B)
    # is said to block C. Note that if a package is a blocker, but it
    # has no dependencies, then it's "blocks" list will be empty.
    voluptuous.Required("blocked_by"): [_nonempty_string],
    voluptuous.Required("sloc_info"): voluptuous.Schema({ _nonempty_string: int }),
    voluptuous.Required("red_output"): [ _red_record ],
    voluptuous.Required("errors"): list,
    # Information about various tools: were they invoked for this build,
    # what were their return codes
    voluptuous.Required("tool_information"): voluptuous.Schema({
        voluptuous.Required("configure"): voluptuous.Schema({
            voluptuous.Required("used"): bool,
            voluptuous.Required("success"): voluptuous.Any(None, bool),
            voluptuous.Required("autoconf"): bool,
        }),
        voluptuous.Required("cmake"): voluptuous.Schema({
            voluptuous.Required("used"): bool,
            voluptuous.Required("success"): voluptuous.Any(None, bool),
        })
    }),
    voluptuous.Required("category_counts"): voluptuous.Schema({
        voluptuous.Any(*_categories): int
    }),
    # This counts the total number of errors that had a semantic in each
    # category, over the whole build.
    # e.g.
    # missing_header ->
    #   stddef.h -> 1
    #   iconv.h -> 3
    # configure_error ->
    #   ...
    voluptuous.Required("semantics_counts"): voluptuous.Schema({
        voluptuous.Any(*_categories): voluptuous.Schema({
            _nonempty_string: int
        })
    }),
    voluptuous.Required("red_errors"): voluptuous.Schema({
        "hardcoded invocation": voluptuous.Schema({ _nonempty_string: int }),
        "malformed path": voluptuous.Schema({ _nonempty_string: int }),
        "empty path": voluptuous.Schema({ "": int }),
        "PATH not in env!": voluptuous.Schema({ "": int })
    }),
    # The page-unique id of the line that is the last line of the build
    # log (not the entire log, just the log whose header is the makepkg
    # command). This is useful to scroll to there directly, to find
    # errors.
    voluptuous.Required("last_build_log_line"): int,
    voluptuous.Required("log"): [
        voluptuous.Schema({
            voluptuous.Required("head"): _nonempty_string,
            voluptuous.Required("kind"): voluptuous.Any("command", "info", "die"),
            voluptuous.Required("time"): (lambda s:
                datetime.datetime.strptime(s, "%Y-%m-%dT%H:%M:%S")),
            # Post-processing looks through the output of commands, and
            # decorates each line by transforming them from strings into
            # dictionaries.  For each line in the command output, the
            # line goes into the "text" key. The "category" key is used
            # to describe what kind of error that line represents, if
            # any. The valid categories are those defined in
            # classification_patterns.yaml, or None if the line is not
            # an error message.
            voluptuous.Required("body"): [voluptuous.Schema({
                voluptuous.Required("text"): _string,
                voluptuous.Required("id"): int,
                voluptuous.Required("category"): voluptuous.Any(None,
                    *_categories),
                voluptuous.Required("semantics"): voluptuous.Schema({
                    _nonempty_string: _nonempty_string
                })
            })]
        })
    ]
})

"""voluptuous.Schema for error classification patterns"""
classification_schema = voluptuous.Schema([voluptuous.Schema({
    # A regex to match a line from the build log against. If the line
    # matches the pattern, it will be classified as 'category'. If the
    # pattern contains one or more _named_ subgroups, then the
    # post-processed log line will contain a hash as the value of the
    # 'semantics' key; each key of the hash will be the name of a
    # subgroup, and the value will be the value of that subgroup.
    #
    # E.g. if we have:
    #     pattern: ": (?P<file>.+?): cannot execute binary file"
    #     category: "exec_error"
    # And a line from the log file:
    #     Horrible error: ./a.out: cannot execute binary file
    # Then post-processing will turn that line into
    #    {"text": "Horrible error: ./a.out: cannot execute binary file",
    #     "category": "exec_error",
    #     "semantics": {"file": "./a.out"}}
    voluptuous.Required("pattern"): _nonempty_string,
    voluptuous.Required("category"): _nonempty_string,
})])


"""tool_redirect_rules.yaml files for individual toolchains

These are used for specifying what native tools will be overwritten by
a compiler wrapper that prints an error message and redirects the
invocation to a toolchain tool.
"""
tool_redirect_schema = voluptuous.Schema({
    # Directory where toolchain tools are located; this will be appended
    # to the front of $PATH.
    voluptuous.Required("bin-dir"): voluptuous.Any(_nonempty_string, None),
    # Prefix that is common to all toolchain tools.
    voluptuous.Required("prefix"): _string,
    # A list of executables E such that /usr/bin/E shall be replaced by a
    # wrapper that points to B/E, where B is the value of the "bin" field
    voluptuous.Required("overwrite"): [ _nonempty_string ],
    # A map from N -> E such that /usr/bin/N shall be replaced by a
    # wrapper that points to B/E, where B is the value of the "bin" field
    voluptuous.Required("replacements"): {
        _nonempty_string: _nonempty_string
    }
})
